// Generated by IB v0.3.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate

@end


@implementation MainController

@end


@implementation AppDelegate

@end



