// Generated by IB v0.3.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface AppDelegate





-(IBAction) applicationDidFinishLaunching:(id) notification;
-(IBAction) buildWindow;

@end


@interface MainController: NSViewController





-(IBAction) init;
-(IBAction) loadView;
-(IBAction) numberOfRowsInListView:(id) view;
-(IBAction) listViewSelectionDidChange:(id) notification;

@end


@interface AppDelegate





-(IBAction) buildMenu;

@end



